title: Johan Althoff - CV
description: Professional resources
baseurl: "/cv"
url: "https://teetow.com"
markdown: kramdown
include:
  - "*.md"
  - "*.pdf"
  - "public/*.md"
  - "public/*.pdf"
favicon: /assets/favicon.svg
