name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      
      - name: Generate PDF files
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: cv.md
          output_dir: ./
          build_html: false

      - name: Deploy
        if: ${{ !github.event.act }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: ".github,*.py"
