name: GitHub Pages

env:
  ACT: false

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ env.ACT != 'true' }}
        uses: actions/checkout@v4

      - name: Generate PDF files
        run: |
          # Generate PDFs for all markdown files in the public directory
          echo "Generating PDFs from markdown files"
          
          # Convert each markdown file to PDF with proper naming
          for md_file in public/*.md; do
            basename=$(basename "$md_file" .md)
            echo "Converting $md_file to public/johan_althoff_$basename.pdf"
            
            docker run --rm \
              -v "$(pwd):/workdir" \
              -w /workdir \
              pandoc/latex:latest \
              -f markdown \
              -t pdf \
              "$md_file" \
              -o "public/johan_althoff_$basename.pdf"
          done

      - name: Setup Pages
        if: ${{ env.ACT != 'true' }}
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        if: ${{ env.ACT != 'true' }}
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        if: ${{ env.ACT != 'true' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        if: ${{ env.ACT != 'true' }}
        id: deployment
        uses: actions/deploy-pages@v4
